insert into fournisseur (code_four, nom, pays) values (1, 'Satterfield, Bauch and Terry', null);
insert into fournisseur (code_four, nom, pays) values (2, 'Koelpin, Trantow and Windler', 'Russia');
insert into fournisseur (code_four, nom, pays) values (3, 'Weissnat Group', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (4, 'Zboncak Group', 'El Salvador');
insert into fournisseur (code_four, nom, pays) values (5, 'Langosh, Haley and Fritsch', null);
insert into fournisseur (code_four, nom, pays) values (6, 'Barton, Champlin and Murphy', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (7, 'Lind Inc', 'Albania');
insert into fournisseur (code_four, nom, pays) values (8, 'Harber Group', 'China');
insert into fournisseur (code_four, nom, pays) values (9, 'Dickens and Sons', 'Russia');
insert into fournisseur (code_four, nom, pays) values (10, 'O''Conner, Funk and Hahn', 'Colombia');
insert into fournisseur (code_four, nom, pays) values (11, 'Zemlak LLC', 'Kyrgyzstan');
insert into fournisseur (code_four, nom, pays) values (12, 'Carroll Group', null);
insert into fournisseur (code_four, nom, pays) values (13, 'Graham, Quitzon and Herzog', 'Jordan');
insert into fournisseur (code_four, nom, pays) values (14, 'Kunde, Stroman and Parker', 'Morocco');
insert into fournisseur (code_four, nom, pays) values (15, 'Weber, Cormier and Bartell', 'China');
insert into fournisseur (code_four, nom, pays) values (16, 'Runte, Upton and Bauch', 'Italy');
insert into fournisseur (code_four, nom, pays) values (17, 'Keebler Group', null);
insert into fournisseur (code_four, nom, pays) values (18, 'Skiles Inc', 'Finland');
insert into fournisseur (code_four, nom, pays) values (19, 'Rowe and Sons', 'Cameroon');
insert into fournisseur (code_four, nom, pays) values (20, 'Smith-Farrell', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (21, 'Bernhard, Adams and Jaskolski', 'United States');
insert into fournisseur (code_four, nom, pays) values (22, 'Windler LLC', null);
insert into fournisseur (code_four, nom, pays) values (23, 'Barrows, Hilll and Hammes', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (24, 'Marvin Group', 'Canada');
insert into fournisseur (code_four, nom, pays) values (25, 'Gorczany, Weber and Farrell', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (26, 'Stokes Group', 'Colombia');
insert into fournisseur (code_four, nom, pays) values (27, 'Purdy-O''Connell', 'China');
insert into fournisseur (code_four, nom, pays) values (28, 'Howell-Cormier', null);
insert into fournisseur (code_four, nom, pays) values (29, 'Koelpin, Durgan and Wisozk', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (30, 'Wilkinson-Hudson', 'China');
insert into fournisseur (code_four, nom, pays) values (31, 'Cartwright, Kautzer and Champlin', null);
insert into fournisseur (code_four, nom, pays) values (32, 'Koss, Waters and Reynolds', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (33, 'Gibson Group', 'Denmark');
insert into fournisseur (code_four, nom, pays) values (34, 'Kemmer LLC', 'Tanzania');
insert into fournisseur (code_four, nom, pays) values (35, 'Schmidt, Will and Nicolas', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (36, 'Wolff Inc', 'Mongolia');
insert into fournisseur (code_four, nom, pays) values (37, 'Marquardt, Kemmer and Graham', 'China');
insert into fournisseur (code_four, nom, pays) values (38, 'Konopelski, Bogan and Spinka', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (39, 'Balistreri-Ankunding', 'China');
insert into fournisseur (code_four, nom, pays) values (40, 'Goyette-Gorczany', 'Russia');
insert into fournisseur (code_four, nom, pays) values (41, 'McDermott, Schultz and Graham', 'China');
insert into fournisseur (code_four, nom, pays) values (42, 'Koch-Turner', 'Vietnam');
insert into fournisseur (code_four, nom, pays) values (43, 'O''Conner, Carroll and Anderson', 'Argentina');
insert into fournisseur (code_four, nom, pays) values (44, 'Breitenberg-Wisoky', 'Iran');
insert into fournisseur (code_four, nom, pays) values (45, 'Hintz Group', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (46, 'Volkman-Torphy', 'Eritrea');
insert into fournisseur (code_four, nom, pays) values (47, 'Hackett-Cartwright', 'China');
insert into fournisseur (code_four, nom, pays) values (48, 'Gutkowski-Lehner', null);
insert into fournisseur (code_four, nom, pays) values (49, 'Little Inc', 'Botswana');
insert into fournisseur (code_four, nom, pays) values (50, 'Macejkovic-Emard', 'China');
insert into fournisseur (code_four, nom, pays) values (51, 'Reinger-Cormier', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (52, 'Hammes and Sons', 'Pakistan');
insert into fournisseur (code_four, nom, pays) values (53, 'Hegmann-Stroman', 'Russia');
insert into fournisseur (code_four, nom, pays) values (54, 'Heaney Group', 'Azerbaijan');
insert into fournisseur (code_four, nom, pays) values (55, 'Dooley Group', 'China');
insert into fournisseur (code_four, nom, pays) values (56, 'Kozey-McDermott', 'Spain');
insert into fournisseur (code_four, nom, pays) values (57, 'Shields-Cummings', 'China');
insert into fournisseur (code_four, nom, pays) values (58, 'Daugherty-Nitzsche', 'China');
insert into fournisseur (code_four, nom, pays) values (59, 'Funk-Luettgen', 'Sweden');
insert into fournisseur (code_four, nom, pays) values (60, 'Weimann-Bailey', 'Serbia');
insert into fournisseur (code_four, nom, pays) values (61, 'Block-Harber', null);
insert into fournisseur (code_four, nom, pays) values (62, 'Mohr-Gibson', 'Togo');
insert into fournisseur (code_four, nom, pays) values (63, 'Shields Inc', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (64, 'Rutherford, McDermott and Okuneva', 'China');
insert into fournisseur (code_four, nom, pays) values (65, 'Kessler, Gislason and Howe', null);
insert into fournisseur (code_four, nom, pays) values (66, 'Schultz-Kris', 'China');
insert into fournisseur (code_four, nom, pays) values (67, 'Miller, Lang and Towne', null);
insert into fournisseur (code_four, nom, pays) values (68, 'Turner, Kassulke and Armstrong', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (69, 'Gleichner, Dickens and Franecki', 'France');
insert into fournisseur (code_four, nom, pays) values (70, 'Bruen, Kozey and Hahn', 'France');
insert into fournisseur (code_four, nom, pays) values (71, 'Hansen Inc', 'France');
insert into fournisseur (code_four, nom, pays) values (72, 'Schmitt, Barrows and Abernathy', 'Argentina');
insert into fournisseur (code_four, nom, pays) values (73, 'Kreiger, Dooley and Weimann', 'China');
insert into fournisseur (code_four, nom, pays) values (74, 'Lynch LLC', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (75, 'Rohan Group', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (76, 'Kunde, Champlin and Grimes', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (77, 'Durgan, Reinger and Wisozk', 'Palestinian Territory');
insert into fournisseur (code_four, nom, pays) values (78, 'Grady Group', 'Pakistan');
insert into fournisseur (code_four, nom, pays) values (79, 'Feil-Durgan', 'China');
insert into fournisseur (code_four, nom, pays) values (80, 'Morissette, Weber and Harvey', 'China');
insert into fournisseur (code_four, nom, pays) values (81, 'McLaughlin, Wiegand and Luettgen', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (82, 'Murray-Prosacco', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (83, 'Welch, Schuster and Robel', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (84, 'Rogahn Inc', 'China');
insert into fournisseur (code_four, nom, pays) values (85, 'Kuhic-Hane', null);
insert into fournisseur (code_four, nom, pays) values (86, 'O''Conner, Flatley and Littel', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (87, 'Dibbert-Cummerata', 'Ukraine');
insert into fournisseur (code_four, nom, pays) values (88, 'Weissnat LLC', 'United States');
insert into fournisseur (code_four, nom, pays) values (89, 'Mohr-Langosh', 'Iran');
insert into fournisseur (code_four, nom, pays) values (90, 'Howe-Gleason', 'China');
insert into fournisseur (code_four, nom, pays) values (91, 'Farrell LLC', 'Italy');
insert into fournisseur (code_four, nom, pays) values (92, 'Raynor and Sons', null);
insert into fournisseur (code_four, nom, pays) values (93, 'Kreiger-Klein', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (94, 'Ratke, Connelly and Zemlak', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (95, 'Veum Inc', 'United Arab Emirates');
insert into fournisseur (code_four, nom, pays) values (96, 'Ebert, Schneider and Jast', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (97, 'Balistreri Group', 'China');
insert into fournisseur (code_four, nom, pays) values (98, 'Nicolas-Koch', 'Russia');
insert into fournisseur (code_four, nom, pays) values (99, 'Ebert-Russel', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (100, 'Erdman, Purdy and Green', 'France');
insert into fournisseur (code_four, nom, pays) values (101, 'Hirthe Inc', null);
insert into fournisseur (code_four, nom, pays) values (102, 'Douglas, Pfannerstill and Lesch', 'China');
insert into fournisseur (code_four, nom, pays) values (103, 'Cole-Bartoletti', 'Malaysia');
insert into fournisseur (code_four, nom, pays) values (104, 'Gislason Group', 'Mexico');
insert into fournisseur (code_four, nom, pays) values (105, 'Volkman-Feil', 'Poland');
insert into fournisseur (code_four, nom, pays) values (106, 'Feest Group', 'Vietnam');
insert into fournisseur (code_four, nom, pays) values (107, 'Ebert-Pagac', 'Taiwan');
insert into fournisseur (code_four, nom, pays) values (108, 'Buckridge, Yost and Schuster', 'China');
insert into fournisseur (code_four, nom, pays) values (109, 'Fahey, Feeney and Konopelski', null);
insert into fournisseur (code_four, nom, pays) values (110, 'Kuhlman-Dibbert', 'China');
insert into fournisseur (code_four, nom, pays) values (111, 'Berge and Sons', 'Sudan');
insert into fournisseur (code_four, nom, pays) values (112, 'Abbott Group', 'Nigeria');
insert into fournisseur (code_four, nom, pays) values (113, 'Bartoletti Inc', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (114, 'Cormier Group', 'Japan');
insert into fournisseur (code_four, nom, pays) values (115, 'Bruen-Schimmel', 'China');
insert into fournisseur (code_four, nom, pays) values (116, 'Hackett, King and Kertzmann', 'Colombia');
insert into fournisseur (code_four, nom, pays) values (117, 'Murray LLC', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (118, 'Raynor, Wilkinson and Bosco', 'Vietnam');
insert into fournisseur (code_four, nom, pays) values (119, 'Kassulke Inc', 'United States');
insert into fournisseur (code_four, nom, pays) values (120, 'Brakus and Sons', null);
insert into fournisseur (code_four, nom, pays) values (121, 'Kuvalis, Batz and Doyle', 'United States');
insert into fournisseur (code_four, nom, pays) values (122, 'Beer, Stracke and Daniel', 'Estonia');
insert into fournisseur (code_four, nom, pays) values (123, 'Bogisich-D''Amore', 'China');
insert into fournisseur (code_four, nom, pays) values (124, 'Schroeder and Sons', 'Poland');
insert into fournisseur (code_four, nom, pays) values (125, 'O''Conner, Hayes and Funk', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (126, 'Berge-Bogan', 'Hungary');
insert into fournisseur (code_four, nom, pays) values (127, 'O''Reilly Group', 'Malaysia');
insert into fournisseur (code_four, nom, pays) values (128, 'Rippin-Dickens', 'China');
insert into fournisseur (code_four, nom, pays) values (129, 'Lubowitz Inc', 'Oman');
insert into fournisseur (code_four, nom, pays) values (130, 'Hickle-Hagenes', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (131, 'Gottlieb and Sons', 'Thailand');
insert into fournisseur (code_four, nom, pays) values (132, 'Considine Inc', 'China');
insert into fournisseur (code_four, nom, pays) values (133, 'Pouros, Lowe and Bergstrom', 'Nigeria');
insert into fournisseur (code_four, nom, pays) values (134, 'Ledner-Pouros', 'Poland');
insert into fournisseur (code_four, nom, pays) values (135, 'Abshire, Ruecker and Leffler', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (136, 'Runte-Witting', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (137, 'Padberg-Brekke', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (138, 'MacGyver, Hane and Johns', null);
insert into fournisseur (code_four, nom, pays) values (139, 'Hudson-Abshire', 'Argentina');
insert into fournisseur (code_four, nom, pays) values (140, 'Olson-Kuphal', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (141, 'Smith LLC', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (142, 'Hayes LLC', 'Mongolia');
insert into fournisseur (code_four, nom, pays) values (143, 'Swift, Walter and Reilly', 'France');
insert into fournisseur (code_four, nom, pays) values (144, 'Larson, Hackett and Hackett', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (145, 'Cremin Group', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (146, 'Fahey-Walter', 'China');
insert into fournisseur (code_four, nom, pays) values (147, 'Wisozk-White', 'Norway');
insert into fournisseur (code_four, nom, pays) values (148, 'Harvey-Hirthe', 'Guatemala');
insert into fournisseur (code_four, nom, pays) values (149, 'Treutel-Kulas', 'China');
insert into fournisseur (code_four, nom, pays) values (150, 'Schimmel, Skiles and Schulist', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (151, 'Feest, Kris and Paucek', 'Ukraine');
insert into fournisseur (code_four, nom, pays) values (152, 'Kreiger, Haag and Nitzsche', 'Armenia');
insert into fournisseur (code_four, nom, pays) values (153, 'Ferry Group', null);
insert into fournisseur (code_four, nom, pays) values (154, 'Anderson-Heidenreich', null);
insert into fournisseur (code_four, nom, pays) values (155, 'Schuppe LLC', 'Bulgaria');
insert into fournisseur (code_four, nom, pays) values (156, 'Johns-Leffler', 'Serbia');
insert into fournisseur (code_four, nom, pays) values (157, 'Herzog, Collins and Gutkowski', 'Russia');
insert into fournisseur (code_four, nom, pays) values (158, 'Thiel, Douglas and Miller', null);
insert into fournisseur (code_four, nom, pays) values (159, 'Yundt and Sons', 'Panama');
insert into fournisseur (code_four, nom, pays) values (160, 'Wilkinson, Schmeler and Ankunding', null);
insert into fournisseur (code_four, nom, pays) values (161, 'Robel Group', 'Mexico');
insert into fournisseur (code_four, nom, pays) values (162, 'Franecki-Marvin', 'Azerbaijan');
insert into fournisseur (code_four, nom, pays) values (163, 'Kovacek-Fadel', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (164, 'Sauer, Conn and Kutch', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (165, 'Collins Group', 'Russia');
insert into fournisseur (code_four, nom, pays) values (166, 'Sawayn-Johnston', 'France');
insert into fournisseur (code_four, nom, pays) values (167, 'Schaden LLC', 'Russia');
insert into fournisseur (code_four, nom, pays) values (168, 'Kuphal, Shanahan and Hayes', 'Argentina');
insert into fournisseur (code_four, nom, pays) values (169, 'Reilly Inc', 'Iraq');
insert into fournisseur (code_four, nom, pays) values (170, 'Schmeler and Sons', 'China');
insert into fournisseur (code_four, nom, pays) values (171, 'Collins and Sons', 'Saudi Arabia');
insert into fournisseur (code_four, nom, pays) values (172, 'Prosacco Group', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (173, 'Rohan, Lindgren and Purdy', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (174, 'Bradtke and Sons', 'Argentina');
insert into fournisseur (code_four, nom, pays) values (175, 'Bednar and Sons', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (176, 'Boehm-Spinka', 'Russia');
insert into fournisseur (code_four, nom, pays) values (177, 'Aufderhar, Nitzsche and Harris', 'Colombia');
insert into fournisseur (code_four, nom, pays) values (178, 'Quitzon, Russel and Stiedemann', 'Japan');
insert into fournisseur (code_four, nom, pays) values (179, 'Sanford-Renner', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (180, 'Homenick Inc', 'Malaysia');
insert into fournisseur (code_four, nom, pays) values (181, 'Hettinger-Streich', null);
insert into fournisseur (code_four, nom, pays) values (182, 'Schmitt Group', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (183, 'Lind, Douglas and Ziemann', null);
insert into fournisseur (code_four, nom, pays) values (184, 'Hickle-Rutherford', 'Ukraine');
insert into fournisseur (code_four, nom, pays) values (185, 'O''Keefe, Heathcote and Mitchell', 'China');
insert into fournisseur (code_four, nom, pays) values (186, 'Grady-Heidenreich', 'Iran');
insert into fournisseur (code_four, nom, pays) values (187, 'Kovacek Inc', null);
insert into fournisseur (code_four, nom, pays) values (188, 'Turcotte and Sons', 'Peru');
insert into fournisseur (code_four, nom, pays) values (189, 'Toy, Kris and Terry', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (190, 'Crooks, Lowe and Stamm', 'China');
insert into fournisseur (code_four, nom, pays) values (191, 'Bartoletti-Boehm', 'Poland');
insert into fournisseur (code_four, nom, pays) values (192, 'Mitchell-Romaguera', 'Chile');
insert into fournisseur (code_four, nom, pays) values (193, 'Block Inc', 'China');
insert into fournisseur (code_four, nom, pays) values (194, 'Hermiston Group', null);
insert into fournisseur (code_four, nom, pays) values (195, 'Cartwright-Abshire', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (196, 'Tromp and Sons', 'China');
insert into fournisseur (code_four, nom, pays) values (197, 'Bartoletti-Keeling', 'Albania');
insert into fournisseur (code_four, nom, pays) values (198, 'Bergstrom, Wolff and Nikolaus', null);
insert into fournisseur (code_four, nom, pays) values (199, 'Denesik-Thiel', 'China');
insert into fournisseur (code_four, nom, pays) values (200, 'Bailey-Durgan', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (201, 'Flatley, Trantow and Gleichner', 'Belarus');
insert into fournisseur (code_four, nom, pays) values (202, 'Gorczany, Bahringer and Mante', 'Colombia');
insert into fournisseur (code_four, nom, pays) values (203, 'Schroeder and Sons', 'United Kingdom');
insert into fournisseur (code_four, nom, pays) values (204, 'Beier-Kilback', 'China');
insert into fournisseur (code_four, nom, pays) values (205, 'Hauck, Leffler and Gleason', 'Colombia');
insert into fournisseur (code_four, nom, pays) values (206, 'Walsh-Kling', null);
insert into fournisseur (code_four, nom, pays) values (207, 'Bahringer-Schiller', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (208, 'Schaden and Sons', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (209, 'Hilpert, Fisher and Volkman', 'Czech Republic');
insert into fournisseur (code_four, nom, pays) values (210, 'Jones, Ruecker and Doyle', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (211, 'Halvorson-Bradtke', 'France');
insert into fournisseur (code_four, nom, pays) values (212, 'Treutel Inc', 'Isle of Man');
insert into fournisseur (code_four, nom, pays) values (213, 'Rolfson-Lehner', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (214, 'Ebert, Beer and Lang', null);
insert into fournisseur (code_four, nom, pays) values (215, 'Lind Inc', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (216, 'Spencer-Wiza', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (217, 'Willms-Wiza', 'China');
insert into fournisseur (code_four, nom, pays) values (218, 'Hansen-Kihn', 'South Africa');
insert into fournisseur (code_four, nom, pays) values (219, 'Douglas, Parisian and Vandervort', 'Poland');
insert into fournisseur (code_four, nom, pays) values (220, 'Moen Group', null);
insert into fournisseur (code_four, nom, pays) values (221, 'McDermott-Sporer', 'Russia');
insert into fournisseur (code_four, nom, pays) values (222, 'Walsh Inc', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (223, 'Kautzer, Keebler and Boehm', null);
insert into fournisseur (code_four, nom, pays) values (224, 'Harris, Mraz and Howe', 'France');
insert into fournisseur (code_four, nom, pays) values (225, 'Deckow-Howell', 'Brazil');
insert into fournisseur (code_four, nom, pays) values (226, 'Schuppe Group', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (227, 'Aufderhar-Kuphal', 'Croatia');
insert into fournisseur (code_four, nom, pays) values (228, 'McKenzie, Keebler and Rodriguez', 'Sweden');
insert into fournisseur (code_four, nom, pays) values (229, 'O''Keefe Group', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (230, 'Pacocha Inc', 'Spain');
insert into fournisseur (code_four, nom, pays) values (231, 'Bins-Dare', 'Indonesia');
insert into fournisseur (code_four, nom, pays) values (232, 'Stroman, Quitzon and Bergstrom', 'Poland');
insert into fournisseur (code_four, nom, pays) values (233, 'MacGyver Inc', 'Philippines');
insert into fournisseur (code_four, nom, pays) values (234, 'Lowe Inc', 'Mexico');
insert into fournisseur (code_four, nom, pays) values (235, 'Harber Inc', 'Sierra Leone');
insert into fournisseur (code_four, nom, pays) values (236, 'Luettgen Inc', 'Peru');
insert into fournisseur (code_four, nom, pays) values (237, 'Hessel, Heathcote and Roberts', 'Nicaragua');
insert into fournisseur (code_four, nom, pays) values (238, 'Larkin-Swaniawski', 'Finland');
insert into fournisseur (code_four, nom, pays) values (239, 'Luettgen, Hodkiewicz and Ondricka', 'Russia');
insert into fournisseur (code_four, nom, pays) values (240, 'Pouros Group', 'Portugal');
insert into fournisseur (code_four, nom, pays) values (241, 'Schumm, Effertz and Lakin', 'Afghanistan');
insert into fournisseur (code_four, nom, pays) values (242, 'Weimann and Sons', null);
insert into fournisseur (code_four, nom, pays) values (243, 'Champlin Inc', 'China');
insert into fournisseur (code_four, nom, pays) values (244, 'Romaguera Inc', 'France');
insert into fournisseur (code_four, nom, pays) values (245, 'Mayert-King', 'China');
insert into fournisseur (code_four, nom, pays) values (246, 'Nikolaus, Welch and Quigley', 'Mexico');
insert into fournisseur (code_four, nom, pays) values (247, 'Graham-Olson', 'France');
insert into fournisseur (code_four, nom, pays) values (248, 'Hessel, Swaniawski and Christiansen', 'Greece');
insert into fournisseur (code_four, nom, pays) values (249, 'Moore Inc', 'Jordan');
insert into fournisseur (code_four, nom, pays) values (250, 'Mohr, Raynor and Stroman', 'China');
